name = "dostglass"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".open-next/pages"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
# Environment variables buraya eklenecek (Cloudflare dashboard'dan da eklenebilir)
