name = "dostglass"
compatibility_date = "2025-04-01"
pages_build_output_dir = ".open-next/pages"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
# Production environment variables can also be set in the Cloudflare dashboard.
